<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfblog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory
{
    public function getAuthor()
    {
        return $this->getCreator();
    }
    
    public function postInsert($event)
    {
        $message =  sfContext::getInstance()->getMailer()->compose()->setFrom(array(sfConfig::get('app_invoice_mailer_email') => sfConfig::get('app_invoice_mailer_name')))
            ->setTo($pTo)
            ->setSubject($pSubjetc)->setBody($pBody)->setContentType('text/html');
        sfContext::getInstance()->getMailer()->send($message);
        
        $message = sfContext::getInstance()->getMailer()->compose()->setFrom('shadulionweb@gmail.com')->setTo('shaduli.vanimal@gmail.com')
                ->setSubject('Mastering Symfony and Doctrine')
                ->setBody('Hi Thank you for attending training');
        sfContext::getInstance()->getMailer()->send($message);
                
    }
}
