generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Category
    theme:                 redminish
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [name, created_at, updated_at]
        object_actions:
          _edit: ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
