generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Category
    theme:                 redminish
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        name: {label: Category}
      list:
        title: Catgeories
        display: [name, created_at, author]
        object_actions:
          _edit: ~
          _activate: { action: activate }
        actions: ~
        max_per_page: 5
        table_method: getAllWithoutSymfony
      filter:  
        display: [name, author]
      form:    
        display: [name]
      edit:    
        title: 'Edit Group'
        display: [name]
        actions: 
          _save: ~
          _list: { label: Go Back }
          _approve: { action: approve }
      new:     ~
