actAs: 
    Timestampable: ~
    SoftDelete: ~
    Signable: ~
    
Category:
  columns:
    name: { type: string(25), notblank: true, regexp: '/^[a-zA-Z]+$/' }
    is_active: { type: boolean, default: false }
    
Post:
  columns:
    title: { type: string(255), notblank: true }
    category_id: { type: integer }
    body: { type: string(5000), notblank: true }
    published_at: { type: datetime }
  relations:
    Category: { class: Category, local: category_id, foreign: id, type: one, foreignType: many, foreignAlias: Posts }
    
    
    
    